name: CI / CD Action

on:
  release:
    types: [published]

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Docker login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}

      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE}
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $3}'`
          TAG=${TAG:-latest} docker-compose build

      - name: Push docker image
        run: |
          cd ${GITHUB_WORKSPACE}
          export TAG=`echo $GITHUB_REF | awk -F/ '{print $3}'`
          TAG=${TAG:-latest} docker-compose push
