name: CI / CD Action

on: release

jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master

      - name: Docker login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}

      - name: Fetch and save latest tag
        run: |
          cd ${GITHUB_WORKSPACE}
          LAST_TAG=$(git rev-list --tags --max-count=1)
          CURRENT_TAG=$(git tag --contains "${LAST_TAG}" | sort | tail -1)

      - name: Build docker image
        run: |
          TAG=${CURRENT_TAG:-latest} docker-compose build

      - name: Push docker image
        run: |
          TAG=${CURRENT_TAG:-latest} docker-compose push
